spring.application.name=grabitec
# port
server.port=8087


# database
spring.datasource.url=jdbc:postgresql://localhost:5455/grabitec
spring.datasource.username=user_dev
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000


# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=true
spring.flyway.table=flyway_schema_history
spring.flyway.out-of-order=false

spring.thymeleaf.cache=false
spring.web.resources.static-locations=classpath:/static/,file:src/main/resources/static/